In [2]:
conda install pandoc

Retrieving notices: ...working... done
Channels:
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3

  added / updated specs:
    - pandoc


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandoc-2.12                |       hca03da5_3        12.1 MB
    ------------------------------------------------------------
                                           Total:        12.1 MB

The following NEW packages will be INSTALLED:

  pandoc             pkgs/main/osx-arm64::pandoc-2.12-hca03da5_3



Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [3]:
conda insrall xelatex

usage: conda [-h] [-v] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'insrall' (choose from 'activate', 'deactivate', 'clean', 'compare', 'config', 'create', 'env', 'export', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'build', 'content-trust', 'convert', 'debug', 'develop', 'doctor', 'index', 'inspect', 'metapackage', 'render', 'repoquery', 'skeleton', 'pack', 'server', 'repo', 'token', 'verify')

Note: you may need to restart the kernel to use updated packages.

# Import the necessary library

In [ ]:
import pandas as pd
import os
from datetime import datetime, timedelta

# THE FUNCTION BELOW READS THROUGH ALL THE CSV FILES IN OUR LOCAL ENVIRONMENT

In [ ]:
#LETS CREATE A FUNCTION THAT WILL READ THROUGH ALL THE FILES
def load_and_combine_csv(start_date, end_date, file_directory, output_file):
    # Create a date range from start_date to end_date
    date_range = pd.date_range(start=start_date, end=end_date)

    # Initialize a list to hold all the DataFrames
    df_list = []

    # Debugging: Track files loaded and any issues encountered
    loaded_files = []
    missing_files = []
    empty_files = []

    for single_date in date_range:
        file_name = single_date.strftime("%Y-%m-%d") + '.csv'
        file_path = os.path.join(file_directory, file_name)

        if os.path.exists(file_path):
            # Load the CSV file
            df = pd.read_csv(file_path)

            # Check if the loaded DataFrame is empty
            if df.empty:
                empty_files.append(file_name)
            else:
                # Append the DataFrame to the list
                df_list.append(df)
                loaded_files.append(file_name)
        else:
            missing_files.append(file_name)
            print(f"File not found: {file_path}")

    # Combine all DataFrames in the list into a single DataFrame
    combined_df = pd.concat(df_list, ignore_index=True)

    # Save the combined DataFrame to a new CSV file
    combined_df.to_csv(output_file, index=False)
    print(f"Combined file created: {output_file}")

    # Debugging: Print out the debugging information
    print(f"Loaded files: {len(loaded_files)}")
    print(f"Missing files: {missing_files}")
    print(f"Empty files: {empty_files}")

# Define your parameters
start_date = '2020-01-01'
end_date = '2020-09-30'
file_directory = '/Users/danielabutu/Desktop/HDD journals/data_Q1_2023/data_Q1_2020' # Update this with the path to your CSV files
output_file = '/Users/danielabutu/Desktop/HDD journals/data_Q1_2023/Q1_Q3_data.csv'  # Update this with your desired output path

# Run the function
load_and_combine_csv(start_date, end_date, file_directory, output_file)

# Checking if the data contains records for all the months

In [ ]:
import pandas as pd

def check_for_q1_records(file_path):
    # Load a small number of rows to check the structure of the file
    df_sample = pd.read_csv(file_path, nrows=10)
    
    # Check if there is a date column and identify it
    date_column = None
    for column in df_sample.columns:
        if 'date' in column.lower():  # Assuming the date column contains 'date' in its name
            date_column = column
            break

    if date_column is None:
        print("No date column found in the file.")
        return

    # Load only the date column for the entire file to check the date range
    df_date = pd.read_csv(file_path, usecols=[date_column], parse_dates=[date_column])
    
    # Convert the date column to datetime if it's not already
    if not pd.api.types.is_datetime64_any_dtype(df_date[date_column]):
        df_date[date_column] = pd.to_datetime(df_date[date_column], errors='coerce')

    # Drop rows where the date could not be parsed
    df_date.dropna(subset=[date_column], inplace=True)
    
    # Check the date range
    date_min = df_date[date_column].min()
    date_max = df_date[date_column].max()
    print(f"The date range in the file is from {date_min} to {date_max}")

    # Check if the range falls within the Quarter
    if date_min >= pd.Timestamp('2020-01-01') and date_max <= pd.Timestamp('2020-09-30'):
        print("The file contains records for Q4.")
    else:
        print("The file does not contain records exclusively for Q1-Q3.")

# Example usage
file_path = '/Users/danielabutu/Desktop/HDD journals/data_Q1_2023/Q1_Q3_data.csv'  # Update this with the actual file path of your environment
check_for_q1_records(file_path)

In [2]:
import pandas as pd
data = pd.read_csv('Q1_Q3_data.csv')
data

,date,serial_number,model,capacity_bytes,failure,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,...,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2020-10-01,ZLW0EGC6,ST12000NM001G,12000138625024,0,84.0,227296296.0,NaN,NaN,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-10-01,Z305B2QN,ST4000DM000,4000787030016,0,110.0,27060600.0,NaN,NaN,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-10-01,ZJV0XJQ4,ST12000NM0007,12000138625024,0,83.0,214987616.0,NaN,NaN,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-10-01,ZJV0XJQ3,ST12000NM0007,12000138625024,0,82.0,155222208.0,NaN,NaN,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-10-01,20H0A0CXF97G,TOSHIBA MG07ACA14TA,14000519643136,0,100.0,0.0,100.0,0.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14631130,2020-12-31,ZJV2ESXT,ST12000NM0007,12000138625024,0,80.0,108682728.0,NaN,NaN,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14631131,2020-12-31,ZA13ZBCT,ST8000DM002,8001563222016,0,82.0,152003088.0,NaN,NaN,86.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14631132,2020-12-31,PL1331LAHGD9NH,HGST HMS5C4040BLE640,4000787030016,0,100.0,0.0,134.0,100.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14631133,2020-12-31,PL2331LAHDS4TJ,HGST HMS5C4040BLE640,4000787030016,0,100.0,0.0,133.0,104.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14631134,2020-12-31,X0GEV9EC,WDC WUH721414ALE6L4,14000519643136,0,100.0,0.0,138.0,92.0,85.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN